const employees = [
  {
    id: "1",
     parentId: "",
     name: " John",
     surname: " Doe",
     positionName: " CEO",
     phone: " 555-0101",
     email: " john.doe@company.com",
     team: "",
     location: " New York",
     department: " Executive",
     description: " Chief Executive Officer",
     imageUrl: "/images/1.png",
  },
  {
    id: "2",
     parentId: "1",
     name: " Jane",
     surname: " Smith",
     positionName: " CFO",
     phone: " 555-0102",
     email: " jane.smith@company.com",
     team: "",
     location: " New York",
     department: " Executive",
     description: " Chief Financial Officer",
     imageUrl: "/images/2.png",
  },
  {
    id: "3",
     parentId: "1",
     name: " Mike",
     surname: " Johnson",
     positionName: " CTO",
     phone: " 555-0103",
     email: " mike.johnson@company.com",
     team: "",
     location: " San Francisco",
     department: " Executive",
     description: " Chief Technology Officer",
     imageUrl: "/images/3.png",
  },
  {
    id: "4",
     parentId: "2",
     name: " Emily",
     surname: " Davis",
     positionName: " Finance Manager",
     phone: " 555-0104",
     email: " emily.davis@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Oversees financial operations",
     imageUrl: "/images/4.png",
  },
  {
    id: "5",
     parentId: "3",
     name: " Robert",
     surname: " Brown",
     positionName: " IT Manager",
     phone: " 555-0105",
     email: " robert.brown@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Manages IT infrastructure",
     imageUrl: "/images/1.png",
  },
  {
    id: "6",
     parentId: "4",
     name: " Linda",
     surname: " Wilson",
     positionName: " Accountant",
     phone: " 555-0106",
     email: " linda.wilson@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Handles accounting tasks",
     imageUrl: "/images/2.png",
  },
  {
    id: "7",
     parentId: "5",
     name: " James",
     surname: " Taylor",
     positionName: " System Administrator",
     phone: " 555-0107",
     email: " james.taylor@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Manages system operations",
     imageUrl: "/images/3.png",
  },
  {
    id: "8",
     parentId: "3",
     name: " Sarah",
     surname: " Moore",
     positionName: " Software Engineer",
     phone: " 555-0108",
     email: " sarah.moore@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops software solutions",
     imageUrl: "/images/4.png",
  },
  {
    id: "9",
     parentId: "3",
     name: " David",
     surname: " Anderson",
     positionName: " Data Scientist",
     phone: " 555-0109",
     email: " david.anderson@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Analyzes data trends",
     imageUrl: "/images/1.png",
  },
  {
    id: "10",
     parentId: "4",
     name: " Susan",
     surname: " Thomas",
     positionName: " Financial Analyst",
     phone: " 555-0110",
     email: " susan.thomas@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Analyzes financial data",
     imageUrl: "/images/2.png",
  },
  {
    id: "11",
     parentId: "1",
     name: " Karen",
     surname: " Jackson",
     positionName: " COO",
     phone: " 555-0111",
     email: " karen.jackson@company.com",
     team: "",
     location: " New York",
     department: " Executive",
     description: " Chief Operating Officer",
     imageUrl: "/images/3.png",
  },
  {
    id: "12",
     parentId: "11",
     name: " Brian",
     surname: " White",
     positionName: " Operations Manager",
     phone: " 555-0112",
     email: " brian.white@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Oversees daily operations",
     imageUrl: "/images/4.png",
  },
  {
    id: "13",
     parentId: "11",
     name: " Lisa",
     surname: " Harris",
     positionName: " HR Manager",
     phone: " 555-0113",
     email: " lisa.harris@company.com",
     team: "",
     location: " New York",
     department: " Human Resources",
     description: " Manages HR activities",
     imageUrl: "/images/1.png",
  },
  {
    id: "14",
     parentId: "12",
     name: " Kevin",
     surname: " Martin",
     positionName: " Operations Coordinator",
     phone: " 555-0114",
     email: " kevin.martin@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Coordinates operations tasks",
     imageUrl: "/images/2.png",
  },
  {
    id: "15",
     parentId: "13",
     name: " Nancy",
     surname: " Thompson",
     positionName: " Recruiter",
     phone: " 555-0115",
     email: " nancy.thompson@company.com",
     team: "",
     location: " New York",
     department: " Human Resources",
     description: " Handles recruitment",
     imageUrl: "/images/3.png",
  },
  {
    id: "16",
     parentId: "2",
     name: " Daniel",
     surname: " Garcia",
     positionName: " Controller",
     phone: " 555-0116",
     email: " daniel.garcia@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Manages financial reporting",
     imageUrl: "/images/4.png",
  },
  {
    id: "17",
     parentId: "5",
     name: " Jessica",
     surname: " Martinez",
     positionName: " Network Engineer",
     phone: " 555-0117",
     email: " jessica.martinez@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Maintains network systems",
     imageUrl: "/images/1.png",
  },
  {
    id: "18",
     parentId: "8",
     name: " Charles",
     surname: " Robinson",
     positionName: " Frontend Developer",
     phone: " 555-0118",
     email: " charles.robinson@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops frontend applications",
     imageUrl: "/images/2.png",
  },
  {
    id: "19",
     parentId: "8",
     name: " Patricia",
     surname: " Clark",
     positionName: " Backend Developer",
     phone: " 555-0119",
     email: " patricia.clark@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops backend systems",
     imageUrl: "/images/3.png",
  },
  {
    id: "20",
     parentId: "9",
     name: " Jennifer",
     surname: " Rodriguez",
     positionName: " Data Analyst",
     phone: " 555-0120",
     email: " jennifer.rodriguez@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Analyzes data sets",
     imageUrl: "/images/4.png",
  },
  {
    id: "21",
     parentId: "3",
     name: " Matthew",
     surname: " Lewis",
     positionName: " AI Specialist",
     phone: " 555-0121",
     email: " matthew.lewis@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops AI models",
     imageUrl: "/images/1.png",
  },
  {
    id: "22",
     parentId: "21",
     name: " Barbara",
     surname: " Lee",
     positionName: " Machine Learning Engineer",
     phone: " 555-0122",
     email: " barbara.lee@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Implements ML algorithms",
     imageUrl: "/images/2.png",
  },
  {
    id: "23",
     parentId: "21",
     name: " Paul",
     surname: " Walker",
     positionName: " Data Engineer",
     phone: " 555-0123",
     email: " paul.walker@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Builds data pipelines",
     imageUrl: "/images/3.png",
  },
  {
    id: "24",
     parentId: "5",
     name: " Steven",
     surname: " Hall",
     positionName: " Security Analyst",
     phone: " 555-0124",
     email: " steven.hall@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Ensures IT security",
     imageUrl: "/images/4.png",
  },
  {
    id: "25",
     parentId: "4",
     name: " Laura",
     surname: " Allen",
     positionName: " Tax Specialist",
     phone: " 555-0125",
     email: " laura.allen@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Manages tax compliance",
     imageUrl: "/images/1.png",
  },
  {
    id: "26",
     parentId: "12",
     name: " Anthony",
     surname: " Young",
     positionName: " Logistics Manager",
     phone: " 555-0126",
     email: " anthony.young@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Oversees logistics",
     imageUrl: "/images/2.png",
  },
  {
    id: "27",
     parentId: "13",
     name: " Carol",
     surname: " King",
     positionName: " HR Coordinator",
     phone: " 555-0127",
     email: " carol.king@company.com",
     team: "",
     location: " New York",
     department: " Human Resources",
     description: " Supports HR activities",
     imageUrl: "/images/3.png",
  },
  {
    id: "28",
     parentId: "3",
     name: " Mark",
     surname: " Wright",
     positionName: " Cloud Architect",
     phone: " 555-0128",
     email: " mark.wright@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Designs cloud solutions",
     imageUrl: "/images/4.png",
  },
  {
    id: "29",
     parentId: "28",
     name: " Betty",
     surname: " Scott",
     positionName: " Cloud Engineer",
     phone: " 555-0129",
     email: " betty.scott@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Implements cloud infrastructure",
     imageUrl: "/images/1.png",
  },
  {
    id: "30",
     parentId: "28",
     name: " Sandra",
     surname: " Green",
     positionName: " DevOps Engineer",
     phone: " 555-0130",
     email: " sandra.green@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Manages CI/CD pipelines",
     imageUrl: "/images/2.png",
  },
  {
    id: "31",
     parentId: "5",
     name: " George",
     surname: " Adams",
     positionName: " IT Support Specialist",
     phone: " 555-0131",
     email: " george.adams@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Provides IT support",
     imageUrl: "/images/3.png",
  },
  {
    id: "32",
     parentId: "9",
     name: " Dorothy",
     surname: " Baker",
     positionName: " Statistician",
     phone: " 555-0132",
     email: " dorothy.baker@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Analyzes statistical data",
     imageUrl: "/images/4.png",
  },
  {
    id: "33",
     parentId: "21",
     name: " Jason",
     surname: " Gonzalez",
     positionName: " AI Researcher",
     phone: " 555-0133",
     email: " jason.gonzalez@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Conducts AI research",
     imageUrl: "/images/1.png",
  },
  {
    id: "34",
     parentId: "11",
     name: " Helen",
     surname: " Nelson",
     positionName: " Project Manager",
     phone: " 555-0134",
     email: " helen.nelson@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Manages projects",
     imageUrl: "/images/2.png",
  },
  {
    id: "35",
     parentId: "34",
     name: " Amy",
     surname: " Carter",
     positionName: " Project Coordinator",
     phone: " 555-0135",
     email: " amy.carter@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Coordinates project tasks",
     imageUrl: "/images/3.png",
  },
  {
    id: "36",
     parentId: "2",
     name: " Frank",
     surname: " Mitchell",
     positionName: " Treasurer",
     phone: " 555-0136",
     email: " frank.mitchell@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Manages treasury operations",
     imageUrl: "/images/4.png",
  },
  {
    id: "37",
     parentId: "13",
     name: " Rebecca",
     surname: " Perez",
     positionName: " HR Assistant",
     phone: " 555-0137",
     email: " rebecca.perez@company.com",
     team: "",
     location: " New York",
     department: " Human Resources",
     description: " Assists with HR tasks",
     imageUrl: "/images/1.png",
  },
  {
    id: "38",
     parentId: "8",
     name: " Harold",
     surname: " Roberts",
     positionName: " UX Designer",
     phone: " 555-0138",
     email: " harold.roberts@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Designs user interfaces",
     imageUrl: "/images/2.png",
  },
  {
    id: "39",
     parentId: "8",
     name: " Brenda",
     surname: " Turner",
     positionName: " UI Designer",
     phone: " 555-0139",
     email: " brenda.turner@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Designs user experiences",
     imageUrl: "/images/3.png",
  },
  {
    id: "40",
     parentId: "9",
     name: " Scott",
     surname: " Phillips",
     positionName: " Data Visualization Specialist",
     phone: " 555-0140",
     email: " scott.phillips@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Creates data visualizations",
     imageUrl: "/images/4.png",
  },
  {
    id: "41",
     parentId: "5",
     name: " Eric",
     surname: " Campbell",
     positionName: " IT Technician",
     phone: " 555-0141",
     email: " eric.campbell@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Maintains IT equipment",
     imageUrl: "/images/1.png",
  },
  {
    id: "42",
     parentId: "21",
     name: " Maria",
     surname: " Parker",
     positionName: " NLP Engineer",
     phone: " 555-0142",
     email: " maria.parker@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops NLP models",
     imageUrl: "/images/2.png",
  },
  {
    id: "43",
     parentId: "11",
     name: " Larry",
     surname: " Evans",
     positionName: " Quality Assurance Manager",
     phone: " 555-0143",
     email: " larry.evans@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Ensures product quality",
     imageUrl: "/images/3.png",
  },
  {
    id: "44",
     parentId: "43",
     name: " Kathleen",
     surname: " Edwards",
     positionName: " QA Tester",
     phone: " 555-0144",
     email: " kathleen.edwards@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Tests product quality",
     imageUrl: "/images/4.png",
  },
  {
    id: "45",
     parentId: "2",
     name: " Dennis",
     surname: " Collins",
     positionName: " Audit Manager",
     phone: " 555-0145",
     email: " dennis.collins@company.com",
     team: "",
     location: " New York",
     department: " Finance",
     description: " Manages audits",
     imageUrl: "/images/1.png",
  },
  {
    id: "46",
     parentId: "5",
     name: " Pamela",
     surname: " Stewart",
     positionName: " IT Analyst",
     phone: " 555-0146",
     email: " pamela.stewart@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Analyzes IT systems",
     imageUrl: "/images/2.png",
  },
  {
    id: "47",
     parentId: "21",
     name: " Jerry",
     surname: " Sanchez",
     positionName: " Robotics Engineer",
     phone: " 555-0147",
     email: " jerry.sanchez@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Develops robotic systems",
     imageUrl: "/images/3.png",
  },
  {
    id: "48",
     parentId: "11",
     name: " Willie",
     surname: " Morris",
     positionName: " Supply Chain Manager",
     phone: " 555-0148",
     email: " willie.morris@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Manages supply chain",
     imageUrl: "/images/4.png",
  },
  {
    id: "49",
     parentId: "48",
     name: " Anna",
     surname: " Rogers",
     positionName: " Procurement Specialist",
     phone: " 555-0149",
     email: " anna.rogers@company.com",
     team: "",
     location: " New York",
     department: " Operations",
     description: " Handles procurement",
     imageUrl: "/images/1.png",
  },
  {
    id: "50",
     parentId: "5",
     name: " Ruth",
     surname: " Reed",
     positionName: " IT Project Manager",
     phone: " 555-0150",
     email: " ruth.reed@company.com",
     team: "",
     location: " San Francisco",
     department: " Technology",
     description: " Manages IT projects",
     imageUrl: "/images/2.png",
  },
  {
    id: "51",
     parentId: "2",
     name: "",
     surname: "",
     positionName: "",
     phone: "",
     email: "",
     team: "HR Team",
     location: "",
     department: "",
     description: "Team Administration & Payroll",
     imageUrl: "",
  },
  {
    id: "52",
     parentId: "51",
     name: "Paolo",
     surname: "Cerminara",
     positionName: "Administration",
     phone: " 555-0151",
     email: "paolocerminara@company.com",
     team: "",
     location: " San Francisco",
     department: " Human Resources",
     description: "Team Administration & Payroll",
     imageUrl: "/images/2.png",
  },
  {
    id: "53",
     parentId: "51",
     name: "Chris",
     surname: "Trille",
     positionName: "Payroll",
     phone: " 555-0152",
     email: "christrille@company.com",
     team: "",
     location: " San Francisco",
     department: " Human Resources",
     description: "Team Administration & Payroll",
     imageUrl: "/images/3.png",
  },
  {
    id: "54",
     parentId: "51",
     name: "Carlos",
     surname: "Puyol",
     positionName: "Human Resources",
     phone: " 555-0153",
     email: "carlospuyol@company.com",
     team: "",
     location: " San Francisco",
     department: " Human Resources",
     description: "Team Administration & Payroll",
     imageUrl: "/images/1.png",
  },
  {
    id: "51",
     parentId: "3",
     name: "",
     surname: "",
     positionName: "",
     phone: "",
     email: "",
     team: "HR Team",
     location: "",
     department: "",
     description: "",
     imageUrl: "",
  },
];

export default employees;
